### ISSUE TITLE
how can i create a tracking page?

### ISSUE THREAD

**Issue by harryp-art** [ShipEngine/shipengine-js#162]
Describe the bug

I want to create brand tracking page in development, my api-key is TEST..........z and this is my code:

```
let data = {
    "tracking_pages": [
      {
        "tracking_number": "890...",
        "carrier_code": "ups",
        "service_code": "ups",
      }
    ]

  };
      var options = {
        method: 'POST',
        url: 'https://api.shipengine.com/v-beta/tracking_page',
        headers: {
          Host: 'api.shipengine.com',
          'API-Key': 'TEST_a1b1c1...z',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      }
      request(options, function (error, response) {
        if (error) throw new Error(error)
        console.log(response.body)
      })
```

but it returns this error

```
{
"request_id": "b3a5190c-1-4099-1-7151179be0d8",
"errors": [
{
"error_source": "shipengine",
"error_type": "security",
"error_code": "unauthorized",
"message": "An API key is required. Please see https://www.shipengine.com/docs/auth"
}
]
}
```

**Comment by AnneOReilly** [comment]
Hey @harryp-art , ShipEngine's sandbox does not currently support the branding features (Logos on labels or the Branded Tracking page).  This is definitely something that we plan to support in the future, but for now you will need to use a production level key to generate a page.  

In case you haven't checked it out yet, here are some helpful doc pages:
[Sandbox](https://www.shipengine.com/docs/sandbox/)
[Branded Tracking Page Example](https://www.shipengine.com/docs/tracking/branded-tracking-page/)
[Branded Tracking Page Response](https://www.shipengine.com/docs/tracking/create-branded-tracking-page/)

As always, feel free to send any support tickets to support@shipengine.com for fast follow-up.

**Comment by harryp-art** [comment]
@AnneOReilly last question please, Where do I get this value "branded_tracking_theme_guid" ?

**Comment by AnneOReilly** [comment]
@harryp-art Sorry for the slow response on here - you get the "branded_tracking_theme_guid" in the ShipEngine UI - you can create a new theme here: https://app.shipengine.com/#/portal/themes

Please make sure to reach out to our support team if you have any further questions!
