### ISSUE TITLE
Dependency Node-Fetch Recently Identified CVE

### ISSUE THREAD

**Issue by TwinkieLover** [ShipEngine/shipengine-js#168]
`npm audit
# npm audit report

node-fetch  <3.1.1
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix --force`
Will install shipengine@0.3.1, which is a breaking change
node_modules/node-fetch
  shipengine  >=1.0.0-alpha.1
  Depends on vulnerable versions of node-fetch
  node_modules/shipengine`

**Comment by fishcharlie** [comment]
Pretty sure this isn't an issue anymore.
