### ISSUE TITLE
Create-label-from-shipment-details doesn't work with customs data

### ISSUE THREAD

**Issue by jrogelstad** [ShipEngine/shipengine-js#173]
Attempting to create a label from shipment data with customs info doesn't work. It throws the error "Please add a description to your customs items" even if you pass a description. This is because the map function in the code below is missing description, and description is required (even though the docs say it isn't).

https://github.com/ShipEngine/shipengine-js/blob/main/src/create-label-from-shipment-details/format-params.ts#L139

**Comment by fishcharlie** [comment]
Looks like this was fixed in https://github.com/ShipEngine/shipengine-js/pull/174?

**Comment by jrogelstad** [comment]
Yes!

**Comment by fishcharlie** [comment]
@jrogelstad Might wanna close it then so everything stays organized and ShipEngine can focus on active issues.
