### ISSUE TITLE
`getRatesWithShipmentDetails` `rateOptions` TypeScript & documentation mismatch

### ISSUE THREAD

**Issue by fishcharlie** [ShipEngine/shipengine-js#182]
According to [this documentation page](https://github.com/ShipEngine/shipengine-js/blob/main/docs/get-rates-with-shipment-details.md), the `rateOptions` can take in a single property for `carrierIds`.

However, when using TypeScript with this, it complains about a bunch of additional missing properties. Either these properties are optional, or they aren't. TypeScript should follow what the documentation says and allow passing in a single `carrierIds` field.

**Comment by AnneOReilly** [comment]
Hello @fishcharlie, we will have the fix for this issue in the next release.
