### ISSUE TITLE
Soap Exception on Create Label

### ISSUE THREAD

**Issue by sajeev-adroitminds** [ShipEngine/shipengine-js#211]
Hi,

Am working on Sandbox environment and getting the Soap exception with no explanation on the reason of the exception.

My code is as follows:
`[HttpPost]
        [ProducesResponseType(typeof(ShippingLabelResponseModel), 200)]
        public async Task<IActionResult> CreateShippingLabel(ShippingLabelModel model)
        {
            var shipengine = new ShipEngine("TEST_CIjvEgxG/ltv4mOaX9tCd6/Sbrn0d0JxVD4Vnf+jbS0");
            var order = _context.Orders.FirstOrDefault(x => x.Id == model.OrderItems.First().OrderId);
            var address = _context.UserShippingAddresses.FirstOrDefault(x => x.Id == order.ShippingAddressId);

            var rateParams = new Params()
            {
                LabelLayout = LabelLayout.FourBySix,
                Shipment = new Shipment()
                {
                    CarrierId = "se-4510604",
                    ServiceCode = "usps_priority_mail",
                    ExternalOrderId = order.Id.ToString(),
                    ShipFrom = new ShipEngineSDK.Common.Address()
                    {
                        Name = "John Doe",
                        AddressLine1 = "4009 Marathon Blvd",
                        CityLocality = "Austin",
                        StateProvince = "TX",
                        PostalCode = "78756",
                        CountryCode = Country.US,
                        Phone = "512-555-5555"
                    },
                    ShipTo = new ShipEngineSDK.Common.Address()
                    {
                        Name = address.FullName,
                        AddressLine1 = address.AddressLine1,
                        CityLocality = address.City,
                        StateProvince = address.State,
                        PostalCode = address.ZipCode,
                        CountryCode = Country.US,
                        Phone = "512-555-5555"
                    },
                },
            };
            foreach (var item in model.OrderItems)
            {
                rateParams.Shipment.Packages = new List<Package>();
                rateParams.Shipment.Packages.Add(
                                            new Package()
                                            {
                                                PackageCode = "package",
                                                Weight = new Weight()
                                                {
                                                    Value = 1,
                                                    Unit = WeightUnit.Pound
                                                }
                                            }
                    );
            }

            var result = await shipengine.CreateLabelFromShipmentDetails(rateParams);
            return Ok(new ShippingLabelResponseModel
            {
                LabelDownLoadUrl = result.LabelDownload.Pdf,
                TrackingNumber = result.TrackingNumber,
                LabelId = result.LabelId,
                ShipDate = DateTime.Now
            });
        }`

**Comment by jpill** [comment]
Hi @sajeev-adroitminds, could you confirm if you're still seeing this behavior? 

There looks to have been an issue on the carrier's staging environment on Monday, but it was resolved later in the day. 

If this is still occurring we can investigate closer, but from what I can see this is no longer a problem.

**Comment by sajeev-adroitminds** [comment]
Thanks for the quick response.
I am testing this and let you know the update.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sajeev-adroitminds** [comment]
Works fine, thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
