### ISSUE TITLE
Cannot read properties of null (reading 'contents')

### ISSUE THREAD

**Issue by cvanem** [ShipEngine/shipengine-js#223]
Null customs object is breaking the ship engine api call.  It looks like there are already 3 pull requests (as of this morning) for a fix for this.  This is breaking our production environment.  Can we please get a fix merged ASAP?  Thanks.

<img width="1776" alt="image" src="https://github.com/ShipEngine/shipengine-js/assets/24579103/3ad59095-3d40-49a1-9ebb-be7798defb61">

**Comment by jejrthompson** [comment]
I second this. Our Production environment is DOWN! What TF ShipEngine folks. Unacceptable.

**Comment by jejrthompson** [comment]
@jpill @KaseyCantu Can you help with this?

**Comment by cvanem** [comment]
PR here that seems to work: #224

**Comment by jejrthompson** [comment]
@AnneOReilly can you help here?

**Comment by AnneOReilly** [comment]
Hey folks - we're taking a look.  We'll post updates as we have them!

**Comment by jejrthompson** [comment]
> Hey folks - we're taking a look. We'll post updates as we have them!

Thank you Anne. Chris has submitted a PR that will solve the issue. I have an outage in my PROD env b/c of this.

**Comment by KaseyCantu** [comment]
> @jpill @KaseyCantu Can you help with this?

Hello @jejrthompson - Sorry for the delay in getting PR #224 merged in. I just reviewed and merged in that PR which will prevent null customs items from breaking the code path you are using. I greatly appreciate your patience in all of this and I am so sorry for the inconvenience.

**Comment by KaseyCantu** [comment]
@jejrthompson @cvanem Version `1.0.7` of our SDK has just been published to NPM, please install the latest version to consume these changes. Please let us know if there is anything else we can help out with :octocat:

**Comment by jejrthompson** [comment]
Thank you @KaseyCantu for the assist.
